-- CREATE A DATABASE AND TABLE
-- ASSIGN AN AUTO-INCREMENTING PREMARY KET TO id
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256)
)