-- CREATE A DATABASE AND TABLE
-- ASSIGN AN AUTO-INCREMENTING PREMARY KET TO id
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    State_id INT NOT NULL,
    FOREIGN KEY(state_id) REFERENCES states(id), 
    name VARCHAR(256))
    type=InnoDB;